version: "3"

services:
  postgres:
    image: postgres:12-alpine
    volumes:
      - /var/lib/postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  cachet:
    build:
      context: .
      args:
        - cachet_ver=2.4
    ports:
      - 8000:8000
    links:
      - postgres:postgres
    environment:
      - DB_DRIVER=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=postgres
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_PREFIX=chq_
      - APP_KEY=base64:ghnZ5xQgctz9GIPTan2jqwzU8w7YFWS3mc7zbhxdXGc=
      - APP_LOG=errorlog
      - APP_ENV=${APP_ENV:-production}
      - APP_DEBUG=false
      - DEBUG=false
      - MAIL_DRIVER=sendmail
      - MAIL_HOST=localhost
      - MAIL_PORT=25
      - MAIL_USERNAME=null
      - MAIL_PASSWORD=null
      - MAIL_ADDRESS=noreply@samoffice.com
      - MAIL_NAME=Status | SAM Office BV
      - MAIL_ENCRYPTION=null
    depends_on:
      - postgres
    restart: always
